# Generated by Django 5.2.8 on 2025-11-11 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion_casa', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=50)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('ingredientes', models.TextField(blank=True, null=True)),
                ('tiempo_preparacion', models.IntegerField(verbose_name='Tiempo de preparación (min)')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('idcliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Restaurante.cliente')),
                ('idplatillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_Restaurante.platillo')),
            ],
        ),
    ]
